consul:
  image: consul
  hostname: consul
  ports:
    - "8301:8301"
    - "8302:8302"
    - "8500:8500"
    - "8600:8600"

traefik:
  image: traefik
  hostname: traefik
  volumes:
    - ./traefik.toml:/etc/traefik/traefik.toml
  links:
    - consul
  ports:
    - "8080:8080"
    - "80:80"

