deviceservice:
  image: "device-service:1.0.0"
  hostname: device-service
  environment:
    JAVA_OPTS: -Xmx128m -Dcom.sun.management.jmxremote.port=9080 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false
  ports:
    - "8080:8080"
    - "9080:9080"

roomservice:
  image: "room-service:1.0.0"
  hostname: room-service
  links:
    - deviceservice
  environment:
    JAVA_OPTS: -Xmx128m -Dcom.sun.management.jmxremote.port=9100 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false
  ports:
    - "8100:8100"
    - "9100:9100"
