version: '3'

services:
  portainer:
    image: portainer/portainer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "9000:9000"

  message-queue:
    image: rmohr/activemq:5.14.3
    expose:
      - "61616"       # the JMS port
      - "1883"        # the MQTT port
      - "5672"        # the AMQP port
    ports:
      - "8161:8161"   # the admin web UI
    networks:
      - jee7net

  datagrid-service:
    build: ./microservices/datagrid-service
    image: lreimer/datagrid-service:1.0
    volumes:
      - ./microservices/datagrid-service/src/main/hazelcast/hazelcast_default.xml:/opt/payara/config/hazelcast.xml
    expose:
      - "5701"        # the outbound Hazelcast port
      - "54327"       # the multicast Hazelcast port
    ports:
      - "18080:8080"  # the HTTP endpoint
    networks:
      - jee7net

  process-service:
    build: ./microservices/process-service
    image: lreimer/process-service:1.2
    environment:
      - org_apache_deltaspike_ProjectStage=Development
    volumes:
      - ./microservices/process-service/src/main/hazelcast/hazelcast_default.xml:/process-service/config/hazelcast.xml
    expose:
      - "5701"        # the outbound Hazelcast port
      - "54327"       # the multicast Hazelcast port
    ports:
      - "18081:8080"  # the HTTP endpoint
    depends_on:
      - datagrid-service
      - process-db
    networks:
      - jee7net

  billing-service:
    build: ./microservices/billing-service
    image: lreimer/billing-service:1.2
    environment:
      - org_apache_deltaspike_ProjectStage=Development
    volumes:
      - ./microservices/billing-service/src/main/hazelcast/hazelcast_default.xml:/billing-service/config/hazelcast.xml
    expose:
      - "5701"        # the outbound Hazelcast port
      - "54327"       # the multicast Hazelcast port
    ports:
      - "18082:8080"  # the HTTP endpoint
    depends_on:
      - datagrid-service
      - process-service
      - billing-db
    networks:
      - jee7net

  payment-service:
    build: ./microservices/payment-service
    image: lreimer/payment-service:1.2
    environment:
      - org_apache_deltaspike_ProjectStage=Development
    volumes:
      - ./microservices/payment-service/src/main/hazelcast/hazelcast_default.xml:/payment-service/config/hazelcast.xml
    expose:
      - "5701"        # the outbound Hazelcast port
      - "54327"       # the multicast Hazelcast port
    ports:
      - "18083:8080"  # the HTTP endpoint
    depends_on:
      - datagrid-service
      - process-service
      - payment-db
    networks:
      - jee7net

  process-db:
    image: "postgres:9.6.3"
    environment:
      - POSTGRES_USER=process
      - POSTGRES_PASSWORD=12qwasyx
    ports:
      - "15432:5432"
    networks:
      - jee7net

  billing-db:
    image: "postgres:9.6.3"
    environment:
      - POSTGRES_USER=billing
      - POSTGRES_PASSWORD=12qwasyx
    ports:
      - "25432:5432"
    networks:
      - jee7net

  payment-db:
    image: "postgres:9.6.3"
    environment:
      - POSTGRES_USER=payment
      - POSTGRES_PASSWORD=12qwasyx
    ports:
      - "35432:5432"
    networks:
      - jee7net

networks:
  jee7net:
    driver: bridge
