version: '3'

services:
  portainer:
    image: portainer/portainer
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
    - "9000:9000"

  message-queue:
    image: rmohr/activemq:5.14.3
    expose:
      - "61616"       # the JMS port
    ports:
      - "8161:8161"   # the admin web UI
    networks:
      - jee7net

  process-db:
    image: "postgres:9.6.3"
    environment:
    - POSTGRES_USER=process
    - POSTGRES_PASSWORD=12qwasyx
    ports:
    - "15432:5432"
    networks:
    - jee7net

  billing-db:
    image: "postgres:9.6.3"
    environment:
    - POSTGRES_USER=billing
    - POSTGRES_PASSWORD=12qwasyx
    ports:
    - "25432:5432"
    networks:
    - jee7net

  payment-db:
    image: "postgres:9.6.3"
    environment:
    - POSTGRES_USER=payment
    - POSTGRES_PASSWORD=12qwasyx
    ports:
    - "35432:5432"
    networks:
    - jee7net

networks:
  networks:
    jee7net:
      driver: bridge
