apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: billing-service
    hazelcast: enabled
  name: billing-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.kompose.service: billing-service
        hazelcast: enabled
    spec:
      containers:
      - image: lreimer/billing-service:1.2
        name: billing-service
        ports:
        - containerPort: 8080
        - containerPort: 5701
        livenessProbe:
          httpGet:
            path: /admin/ping
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /admin/healthcheck
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
        volumeMounts:
        - mountPath: /billing-service/config/
          name: billing-service-config-volume
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: billing-service-config-volume
        configMap:
          name: billing-service-config
