apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: process-service
    hazelcast: enabled
  name: process-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.kompose.service: process-service
        hazelcast: enabled
    spec:
      containers:
      - image: lreimer/process-service:1.2
        name: process-service
        ports:
        - containerPort: 8080
        - containerPort: 5701
        livenessProbe:
          httpGet:
            path: /admin/ping
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /admin/healthcheck
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
        volumeMounts:
        - mountPath: /process-service/config/
          name: process-service-config-volume
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: process-service-config-volume
        configMap:
          name: process-service-config
