apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    io.kompose.service: billing-service
    hazelcast: enabled
  name: billing-service
spec:
  replicas: 1
  selector:
    io.kompose.service: billing-service
  template:
    metadata:
      labels:
        io.kompose.service: billing-service
        hazelcast: enabled
    spec:
      containers:
      - image: ' '
        name: billing-service
        ports:
        - containerPort: 8080
        - containerPort: 5701
        livenessProbe:
          httpGet:
            path: /api/application.wadl
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
        resources: {}
        volumeMounts:
        - mountPath: /billing-service/config/
          name: billing-service-config-volume
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: billing-service-config-volume
        configMap:
          name: billing-service-config
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - billing-service
      from:
        kind: ImageStreamTag
        name: billing-service:2.0
    type: ImageChange
